// Generated by gencpp from file roslisp_tutorials_turtles/move.msg
// DO NOT EDIT!


#ifndef ROSLISP_TUTORIALS_TURTLES_MESSAGE_MOVE_H
#define ROSLISP_TUTORIALS_TURTLES_MESSAGE_MOVE_H

#include <ros/service_traits.h>


#include <roslisp_tutorials_turtles/moveRequest.h>
#include <roslisp_tutorials_turtles/moveResponse.h>


namespace roslisp_tutorials_turtles
{

struct move
{

typedef moveRequest Request;
typedef moveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct move
} // namespace roslisp_tutorials_turtles


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roslisp_tutorials_turtles::move > {
  static const char* value()
  {
    return "b2cb89f922c5d07784b533cfabb72389";
  }

  static const char* value(const ::roslisp_tutorials_turtles::move&) { return value(); }
};

template<>
struct DataType< ::roslisp_tutorials_turtles::move > {
  static const char* value()
  {
    return "roslisp_tutorials_turtles/move";
  }

  static const char* value(const ::roslisp_tutorials_turtles::move&) { return value(); }
};


// service_traits::MD5Sum< ::roslisp_tutorials_turtles::moveRequest> should match
// service_traits::MD5Sum< ::roslisp_tutorials_turtles::move >
template<>
struct MD5Sum< ::roslisp_tutorials_turtles::moveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roslisp_tutorials_turtles::move >::value();
  }
  static const char* value(const ::roslisp_tutorials_turtles::moveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roslisp_tutorials_turtles::moveRequest> should match
// service_traits::DataType< ::roslisp_tutorials_turtles::move >
template<>
struct DataType< ::roslisp_tutorials_turtles::moveRequest>
{
  static const char* value()
  {
    return DataType< ::roslisp_tutorials_turtles::move >::value();
  }
  static const char* value(const ::roslisp_tutorials_turtles::moveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roslisp_tutorials_turtles::moveResponse> should match
// service_traits::MD5Sum< ::roslisp_tutorials_turtles::move >
template<>
struct MD5Sum< ::roslisp_tutorials_turtles::moveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roslisp_tutorials_turtles::move >::value();
  }
  static const char* value(const ::roslisp_tutorials_turtles::moveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roslisp_tutorials_turtles::moveResponse> should match
// service_traits::DataType< ::roslisp_tutorials_turtles::move >
template<>
struct DataType< ::roslisp_tutorials_turtles::moveResponse>
{
  static const char* value()
  {
    return DataType< ::roslisp_tutorials_turtles::move >::value();
  }
  static const char* value(const ::roslisp_tutorials_turtles::moveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSLISP_TUTORIALS_TURTLES_MESSAGE_MOVE_H
