// Generated by gencpp from file roslisp_tutorials_turtles/moveRequest.msg
// DO NOT EDIT!


#ifndef ROSLISP_TUTORIALS_TURTLES_MESSAGE_MOVEREQUEST_H
#define ROSLISP_TUTORIALS_TURTLES_MESSAGE_MOVEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roslisp_tutorials_turtles
{
template <class ContainerAllocator>
struct moveRequest_
{
  typedef moveRequest_<ContainerAllocator> Type;

  moveRequest_()
    : distance(0)  {
    }
  moveRequest_(const ContainerAllocator& _alloc)
    : distance(0)  {
  (void)_alloc;
    }



   typedef uint32_t _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::roslisp_tutorials_turtles::moveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roslisp_tutorials_turtles::moveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct moveRequest_

typedef ::roslisp_tutorials_turtles::moveRequest_<std::allocator<void> > moveRequest;

typedef boost::shared_ptr< ::roslisp_tutorials_turtles::moveRequest > moveRequestPtr;
typedef boost::shared_ptr< ::roslisp_tutorials_turtles::moveRequest const> moveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roslisp_tutorials_turtles::moveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roslisp_tutorials_turtles::moveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roslisp_tutorials_turtles::moveRequest_<ContainerAllocator1> & lhs, const ::roslisp_tutorials_turtles::moveRequest_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roslisp_tutorials_turtles::moveRequest_<ContainerAllocator1> & lhs, const ::roslisp_tutorials_turtles::moveRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roslisp_tutorials_turtles

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::roslisp_tutorials_turtles::moveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roslisp_tutorials_turtles::moveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roslisp_tutorials_turtles::moveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roslisp_tutorials_turtles::moveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roslisp_tutorials_turtles::moveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roslisp_tutorials_turtles::moveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roslisp_tutorials_turtles::moveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b2cb89f922c5d07784b533cfabb72389";
  }

  static const char* value(const ::roslisp_tutorials_turtles::moveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb2cb89f922c5d077ULL;
  static const uint64_t static_value2 = 0x84b533cfabb72389ULL;
};

template<class ContainerAllocator>
struct DataType< ::roslisp_tutorials_turtles::moveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roslisp_tutorials_turtles/moveRequest";
  }

  static const char* value(const ::roslisp_tutorials_turtles::moveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roslisp_tutorials_turtles::moveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 distance\n"
;
  }

  static const char* value(const ::roslisp_tutorials_turtles::moveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roslisp_tutorials_turtles::moveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct moveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roslisp_tutorials_turtles::moveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roslisp_tutorials_turtles::moveRequest_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSLISP_TUTORIALS_TURTLES_MESSAGE_MOVEREQUEST_H
