// Generated by gencpp from file roslisp_tutorials_turtles/turn.msg
// DO NOT EDIT!


#ifndef ROSLISP_TUTORIALS_TURTLES_MESSAGE_TURN_H
#define ROSLISP_TUTORIALS_TURTLES_MESSAGE_TURN_H

#include <ros/service_traits.h>


#include <roslisp_tutorials_turtles/turnRequest.h>
#include <roslisp_tutorials_turtles/turnResponse.h>


namespace roslisp_tutorials_turtles
{

struct turn
{

typedef turnRequest Request;
typedef turnResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct turn
} // namespace roslisp_tutorials_turtles


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roslisp_tutorials_turtles::turn > {
  static const char* value()
  {
    return "4edb55038e2b888976a0c0c56935341c";
  }

  static const char* value(const ::roslisp_tutorials_turtles::turn&) { return value(); }
};

template<>
struct DataType< ::roslisp_tutorials_turtles::turn > {
  static const char* value()
  {
    return "roslisp_tutorials_turtles/turn";
  }

  static const char* value(const ::roslisp_tutorials_turtles::turn&) { return value(); }
};


// service_traits::MD5Sum< ::roslisp_tutorials_turtles::turnRequest> should match
// service_traits::MD5Sum< ::roslisp_tutorials_turtles::turn >
template<>
struct MD5Sum< ::roslisp_tutorials_turtles::turnRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roslisp_tutorials_turtles::turn >::value();
  }
  static const char* value(const ::roslisp_tutorials_turtles::turnRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roslisp_tutorials_turtles::turnRequest> should match
// service_traits::DataType< ::roslisp_tutorials_turtles::turn >
template<>
struct DataType< ::roslisp_tutorials_turtles::turnRequest>
{
  static const char* value()
  {
    return DataType< ::roslisp_tutorials_turtles::turn >::value();
  }
  static const char* value(const ::roslisp_tutorials_turtles::turnRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roslisp_tutorials_turtles::turnResponse> should match
// service_traits::MD5Sum< ::roslisp_tutorials_turtles::turn >
template<>
struct MD5Sum< ::roslisp_tutorials_turtles::turnResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roslisp_tutorials_turtles::turn >::value();
  }
  static const char* value(const ::roslisp_tutorials_turtles::turnResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roslisp_tutorials_turtles::turnResponse> should match
// service_traits::DataType< ::roslisp_tutorials_turtles::turn >
template<>
struct DataType< ::roslisp_tutorials_turtles::turnResponse>
{
  static const char* value()
  {
    return DataType< ::roslisp_tutorials_turtles::turn >::value();
  }
  static const char* value(const ::roslisp_tutorials_turtles::turnResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSLISP_TUTORIALS_TURTLES_MESSAGE_TURN_H
