// Generated by gencpp from file roslisp_tutorials_turtles/turnRequest.msg
// DO NOT EDIT!


#ifndef ROSLISP_TUTORIALS_TURTLES_MESSAGE_TURNREQUEST_H
#define ROSLISP_TUTORIALS_TURTLES_MESSAGE_TURNREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roslisp_tutorials_turtles
{
template <class ContainerAllocator>
struct turnRequest_
{
  typedef turnRequest_<ContainerAllocator> Type;

  turnRequest_()
    : angle(0.0)  {
    }
  turnRequest_(const ContainerAllocator& _alloc)
    : angle(0.0)  {
  (void)_alloc;
    }



   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::roslisp_tutorials_turtles::turnRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roslisp_tutorials_turtles::turnRequest_<ContainerAllocator> const> ConstPtr;

}; // struct turnRequest_

typedef ::roslisp_tutorials_turtles::turnRequest_<std::allocator<void> > turnRequest;

typedef boost::shared_ptr< ::roslisp_tutorials_turtles::turnRequest > turnRequestPtr;
typedef boost::shared_ptr< ::roslisp_tutorials_turtles::turnRequest const> turnRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roslisp_tutorials_turtles::turnRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roslisp_tutorials_turtles::turnRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roslisp_tutorials_turtles::turnRequest_<ContainerAllocator1> & lhs, const ::roslisp_tutorials_turtles::turnRequest_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roslisp_tutorials_turtles::turnRequest_<ContainerAllocator1> & lhs, const ::roslisp_tutorials_turtles::turnRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roslisp_tutorials_turtles

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::roslisp_tutorials_turtles::turnRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roslisp_tutorials_turtles::turnRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roslisp_tutorials_turtles::turnRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roslisp_tutorials_turtles::turnRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roslisp_tutorials_turtles::turnRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roslisp_tutorials_turtles::turnRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roslisp_tutorials_turtles::turnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4edb55038e2b888976a0c0c56935341c";
  }

  static const char* value(const ::roslisp_tutorials_turtles::turnRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4edb55038e2b8889ULL;
  static const uint64_t static_value2 = 0x76a0c0c56935341cULL;
};

template<class ContainerAllocator>
struct DataType< ::roslisp_tutorials_turtles::turnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roslisp_tutorials_turtles/turnRequest";
  }

  static const char* value(const ::roslisp_tutorials_turtles::turnRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roslisp_tutorials_turtles::turnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 angle\n"
;
  }

  static const char* value(const ::roslisp_tutorials_turtles::turnRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roslisp_tutorials_turtles::turnRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct turnRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roslisp_tutorials_turtles::turnRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roslisp_tutorials_turtles::turnRequest_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSLISP_TUTORIALS_TURTLES_MESSAGE_TURNREQUEST_H
