#!/usr/bin/env python3

import rospy
import time
from turtlesim.msg import Pose
from turtlesim.srv import TeleportAbsolute
from std_srvs.srv import Empty
from geometry_msgs.msg import Twist, Vector3
# from turtle_hw.srv import Start
from roslisp_tutorials_turtles.msg import velocity
from roslisp_tutorials_turtles.srv import move, turn, moveResponse, turnResponse
from numpy import pi
from math import sqrt, atan2, pow, fabs

PI = 3.14159265358979323846

teleport = rospy.ServiceProxy("turtle1/teleport_absolute", TeleportAbsolute)
draw = rospy.ServiceProxy("draw", Empty)
# waypoints = rospy.get_param("/talker/waypoint")


class navigaition:

    def __init__(self):
        self.curr_pose = Pose()
        # self.listener = rospy.Subscriber('turtle1/pose', Pose, self.pose_update)
        self.curr_pose = rospy.Subscriber('turtle1/pose', Pose, self.pose_update)
        # self.publsher = rospy.Publisher('position', Pose, queue_size=10)
        self.default_speed = 3
        # self.curr_pose = self.pose_update()
        self.translate = rospy.Publisher('turtle1/cmd_vel', Twist, queue_size= 10)

    def __eq__(pose1, pose2):
        return pose1.x == pose2.x and pose1.y == pose2.y and pose1.theta == pose2.theta


    def get_pose(self):
        return self.curr_pose

    def get_speed(self):
        return self.default_speed

    def publish(self, vel):
        self.translate.publish(vel)

    def pose_update(self, pose_data):
        self.curr_pose.x = round(pose_data.x, 4)
        self.curr_pose.y = round(pose_data.y, 4)
        if pose_data.theta < 0: self.curr_pose.theta = pose_data.theta + 2*pi
        else: self.curr_pose.theta = pose_data.theta


def deg2rad(deg): return (deg*PI)/180

#v = d/t then d = v*t then t = d/v    
def mov_handeler(reqdistance):
    #Makes turtle move
    nav = navigaition()
    default_speed = 3
    mov_message = Twist(Vector3(nav.get_speed(), 0, 0), Vector3(0, 0, 0))
    amount_of_time = rospy.Duration.from_sec(reqdistance.distance/nav.get_speed())
    start_time = rospy.Time.now()
    while(rospy.Time.now()-start_time < amount_of_time):
        nav.translate.publish(mov_message)
    return moveResponse()

def turn_handeler(angle):
    #Makes turtle turn
    nav = navigaition()
    turn_message = Twist(Vector3(0, 0, 0), Vector3(0, 0, deg2rad(nav.get_speed())))
    amount_of_time = rospy.Duration.from_sec(angle/nav.get_speed())
    start_time = rospy.Time.now()
    while(rospy.Time.now()-start_time < amount_of_time):
        nav.translate.publish(turn_message)
    return turnResponse()

def save_handeler():
    #returns turtles current position
    nav = navigaition()
    return nav.get_pose()

if __name__ == '__main__':
    try:
        rospy.init_node('navigator')
        mover = rospy.Service('moveme', move, mov_handeler)
        turner = rospy.Service('turnme', turn, turn_handeler)
        # save = rospy.Service('save', Pose, save_handeler)
        # moveing = rospy.ServiceProxy('moveme', move)
        # moveing(10)
        # rospy.log_info("I shouldn't finish here")
        rospy.spin()

    except rospy.ROSInitException:
        # rospy.info("I finished!")
        # rospy.log_info("I finished!")
        pass